/*
 * File: app/view/AddSheet.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AddSheet', {
    extend: 'Ext.Sheet',

    config: {
        id: 'AddSheet',
        enter: 'top',
        stretchX: true,
        stretchY: true,
        items: [
            {
                xtype: 'formpanel',
                height: 352,
                items: [
                    {
                        xtype: 'container',
                        height: 90,
                        html: 'Add an RSS feed URL and a Name. Feed URLs should be in the format: http://feedURL.com',
                        margin: '\'0 0 5 0\'',
                        style: 'text-align: center;',
                        width: '100%'
                    },
                    {
                        xtype: 'textfield',
                        id: 'name',
                        margin: '\'3 0 3 0\'',
                        label: 'Name',
                        name: 'name'
                    },
                    {
                        xtype: 'textfield',
                        id: 'url',
                        margin: '\'3 0 3 0\'',
                        label: 'URL',
                        name: 'url'
                    },
                    {
                        xtype: 'button',
                        id: 'SaveButton',
                        itemId: 'mybutton1',
                        margin: 10,
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        id: 'CancelButton',
                        itemId: 'mybutton2',
                        margin: 10,
                        text: 'Cancel'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onSaveButtonTap',
                event: 'tap',
                delegate: '#SaveButton'
            },
            {
                fn: 'onCancelButtonTap',
                event: 'tap',
                delegate: '#CancelButton'
            }
        ]
    },

    onSaveButtonTap: function(button, e, options) {
        var formPanel = this.down('formpanel');

        var values = formPanel.getValues();

        var store = Ext.data.StoreManager.lookup('FeedStore');

        var record = Ext.ModelMgr.create(values, 'MyApp.model.Feed');

        store.add(record);

        store.sync();

        this.hide();
    },

    onCancelButtonTap: function(button, e, options) {
        this.down('formpanel').reset();
        this.hide();
    }

});