/*
 * File: app/view/MyNavigationView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyNavigationView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.MainView',

    config: {
        items: [
            {
                xtype: 'list',
                id: 'FeedList',
                itemId: 'mylist',
                itemTpl: [
                    '<div>{name}</div>'
                ],
                store: 'FeedStore',
                onItemDisclosure: false,
                preventSelectionOnDisclose: false,
                title: 'FeedBag'
            }
        ],
        navigationBar: {
            items: [
                {
                    xtype: 'button',
                    id: 'addButton',
                    itemId: 'mybutton',
                    text: 'Add',
                    align: 'right'
                }
            ]
        },
        listeners: [
            {
                fn: 'onFeedListItemSwipe',
                event: 'itemswipe',
                delegate: '#FeedList'
            },
            {
                fn: 'onAddButtonTap',
                event: 'tap',
                delegate: '#addButton'
            }
        ]
    },

    onFeedListItemSwipe: function(dataview, index, target, record, e, options) {
        // this is where we should display a delete button
        // swiping left to right should show the button.
    },

    onAddButtonTap: function(button, e, options) {
        var sheet = Ext.getCmp('AddSheet');
        if(!Ext.isDefined(sheet)) {
            sheet = Ext.create('MyApp.view.AddSheet');
            Ext.Viewport.add(sheet);
        }
        sheet.show();
    }

});