/*
 * File: app/controller/FeedController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.FeedController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainView: 'MainView'
        },

        control: {
            "#FeedList": {
                itemtap: 'onListItemTap'
            },
            "feeddetails": {
                itemtap: 'onDataviewItemTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, options) {
        this.createFeedDetailsView(record.get('name'), record.get('url'));
    },

    onDataviewItemTap: function(dataview, index, target, record, e, options) {

        /* This will scroll our selected item into view after a delay of 200 milliseconds. */

        var task = new Ext.util.DelayedTask(function(){
            if (target) {
                dataview.getScrollable().getScroller().scrollTo(0,  target.dom.offsetTop, true);
            }
        }, dataview);
        task.delay(200);
        this.createFeedItemView(record);
    },

    createFeedDetailsView: function(name, url) {
        var newURL = 'http://query.yahooapis.com/v1/public/yql?',
            yql = {
                q: 'select * from rss where url="' + url + '"',
                format: 'json'
            };

        newURL += Ext.Object.toQueryString(yql);
        var details = Ext.create(
        'MyApp.view.FeedDetails', {
            title: name,
            store: Ext.create('MyApp.store.FeedItemStore', {
                proxy: {
                    type: 'jsonp',
                    url: newURL,
                    reader: {
                        type: 'json',
                        rootProperty: 'query.results.item',
                        totalProperty: 'query.count'
                    }
                }
            })
        });
        details.getStore().load();
        this.getMainView().push(details);
    },

    createFeedItemView: function(record) {
        var item = Ext.create(
        'MyApp.view.FeedItem', {
            title: 'Article',
            record: record
        });
        this.getMainView().push(item);
    }

});